---
resource_group_name: ansible-test
location: chinaeast2
azure_deployment_name: azure_deployment_001
recovery_service_template_link: https://raw.githubusercontent.com/github-huzhichao/ansible-tower-samples/main/roles/backupVault/vars/recovery_service_vault_deploy.json
recovery_service_parameters_link : https://raw.githubusercontent.com/github-huzhichao/ansible-tower-samples/main/roles/backupVault/vars/recovery_service_vault_deploy.parameters.json
protected_item_template_link: https://raw.githubusercontent.com/github-huzhichao/ansible-tower-samples/main/roles/backupVault/vars/protected_item_deploy.json
protected_item_parameters_link: https://raw.githubusercontent.com/github-huzhichao/ansible-tower-samples/main/roles/backupVault/vars/protected_item_deploy.parameters.json
