- name: Create Recovery Service Deploy
  azure_rm_deployment:
    resource_group: "{{ resource_group_name }}"
    name: "{{ azure_deployment_name }}"
    location: "{{ location }}"
    template_link: "{{ template_link }}"
    parameters_link: "{{ parameters_link }}"
