- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resource_group_name }}"
    name: "{{ virtual_network_name }}"
    address_prefixes: "10.0.0.0/16"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ resource_group_name }}"
    name: "{{ virtual_subnet_name }}"
    address_prefix: "10.0.1.0/24"
    virtual_network: "{{ virtual_network_name }}"

- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group_name }}"
    allocation_method: Static
    name: "{{ public_ip_name }}"

- name: Create Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ resource_group_name }}"
    name: "{{ nsg_name }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound

- name: Create virtual network interface card
  azure_rm_networkinterface:
    resource_group: "{{ resource_group_name }}"
    name: "{{ nic_name }}"
    virtual_network: "{{ virtual_network_name }}"
    subnet: "{{ virtual_subnet_name }}"
    public_ip_name: "{{ public_ip_name }}"
    security_group: "{{ nsg_name }}"

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group_name }}"
    name: "{{ virtual_machine_name }}"
    vm_size: Standard_D2s_v3
    admin_username: azureuser
    admin_password: 123qwe!@#QWE
    network_interfaces: "{{ nic_name }}"
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.5'
      version: latest
